name: real_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/vectors/illustrations/
    - assets/fonts/google_fonts/
  # fonts:
  #   - family: Mulish
  #     fonts:
  #       - asset: fonts/Raleway-Regular.ttf
  #       - asset: fonts/Raleway-Italic.ttf
  #         style: italic
