// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCisYNiurMC9laF6ARP9LyhEV0ns1LUx-g',
    appId: '1:837851917927:web:b10e226dba8fbd344deec2',
    messagingSenderId: '837851917927',
    projectId: 'chatapparai',
    authDomain: 'chatapparai.firebaseapp.com',
    storageBucket: 'chatapparai.appspot.com',
    measurementId: 'G-H6W5K97Y3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUpROSXiN-58rMwJ3cFBmpk0MiTz08Cs',
    appId: '1:837851917927:android:02e107b91adea5364deec2',
    messagingSenderId: '837851917927',
    projectId: 'chatapparai',
    storageBucket: 'chatapparai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtqUs1duhfqoy0XmSyI2J30vLMd-xY2ZY',
    appId: '1:837851917927:ios:b4226df588686c574deec2',
    messagingSenderId: '837851917927',
    projectId: 'chatapparai',
    storageBucket: 'chatapparai.appspot.com',
    iosClientId: '837851917927-ba3cgoikkrkfbk4v5uie2666jhpncig1.apps.googleusercontent.com',
    iosBundleId: 'com.pamirchat.realProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtqUs1duhfqoy0XmSyI2J30vLMd-xY2ZY',
    appId: '1:837851917927:ios:b4226df588686c574deec2',
    messagingSenderId: '837851917927',
    projectId: 'chatapparai',
    storageBucket: 'chatapparai.appspot.com',
    iosClientId: '837851917927-ba3cgoikkrkfbk4v5uie2666jhpncig1.apps.googleusercontent.com',
    iosBundleId: 'com.pamirchat.realProject',
  );
}
